# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            НКРЯ
tagline:          'Русско-китайский корпус языка'
description:      'Русско-китайский параллельный корпус языка. '
url:              https://kianya.github.io/hyde/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kianya/hyde
