# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Русско-китайский параллельный корпус'
tagline:          'НКРЯ'
description:      'НКРЯ'
url:              https://ruzhcorp.github.io
baseurl:          https://ruzhcorp.github.io/

author:
  name:           'Кирилл Семенов'
  url:            kir.semenow@yandex.ru

paginate:         5

# Custom vars
version:          Beta-0.0.1

github:
  repo:           https://github.com/ruzhcorp
