# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Русско-китайский корпус
tagline:          'A Jekyll theme'
description:      'Русско-китайский параллельный корпус языка. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://kianya.github.io/
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kianya/hyde
